--CREATE TABLE "Favorites"(
--    "id" INT NOT NULL identity,
--    "articleID" INT NOT NULL,
--    "TimesClicked" INT NOT NULL
--);
--ALTER TABLE
--    "Favorites" ADD CONSTRAINT "favorites_id_primary" PRIMARY KEY("id");
--CREATE TABLE "Articles"(
--    "id" INT NOT NULL identity,
--    "newsSource" INT NOT NULL,
--    "image" NVARCHAR(700),
--    "headline" NVARCHAR(500) NOT NULL,
--    "desc" NVARCHAR(700),
--    "link" NVARCHAR(275) NOT NULL
--);
--ALTER TABLE
--    "Articles" ADD CONSTRAINT "articles_id_primary" PRIMARY KEY("id");
--CREATE TABLE "NewsSources"(
--    "id" INT NOT NULL identity,
--    "sourceName" NVARCHAR(255) NOT NULL
--);
--ALTER TABLE
--    "NewsSources" ADD CONSTRAINT "newssources_id_primary" PRIMARY KEY("id");
--CREATE TABLE "Topics"(
--    "id" INT NOT NULL identity,
--    "newsSource" INT NOT NULL,
--    "topicName" NVARCHAR(255) NOT NULL,
--    "RSSLink" NVARCHAR(255) NOT NULL
--);
--ALTER TABLE
--    "Topics" ADD CONSTRAINT "topics_id_primary" PRIMARY KEY("id");
--CREATE TABLE "Config"(
--    "id" INT NOT NULL identity,
--    "logPath" NVARCHAR(255) NOT NULL
--);
--ALTER TABLE
--    "Config" ADD CONSTRAINT "config_id_primary" PRIMARY KEY("id");
--ALTER TABLE
--    "Topics" ADD CONSTRAINT "topics_newssource_foreign" FOREIGN KEY("newsSource") REFERENCES "NewsSources"("id");
--ALTER TABLE
--    "Articles" ADD CONSTRAINT "articles_newssource_foreign" FOREIGN KEY("newsSource") REFERENCES "NewsSources"("id");
--ALTER TABLE
--    "Favorites" ADD CONSTRAINT "favorites_articleid_foreign" FOREIGN KEY("articleID") REFERENCES "Articles"("id");
    
    --create database BreakingNews
    --drop table NewsSources
   --drop table Topics
    --drop table Articles
    --drop table Favorites
    --drop table Config
    -- ADD Additional column to table
    --ALTER TABLE Articles ADD Topic INT
    --ALTER TABLE Articles ADD CONSTRAINT "articles_topic_foreign" FOREIGN KEY("Topic") REFERENCES "Topics"("id");
  

  SELECT * FROM Articles
  SELECT * FROM Topics